[package]
name = "logic"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "dylib"]

[dependencies]
anyhow = "1.0.66"
lazy_static = "1.4.0"
ggez = "0.8.1"
framework = { path = "../framework" }